GET http://localhost:8080/rest

###

GET http://localhost:8080/rest/spruches/?page,size,sort

###

GET http://localhost:8080/rest/spruches

###

POST http://localhost:8080/rest/spruches/

{
    "name": "Susi",
    "text": "halli hallo", 
    "anspruch": 75
}

###

POST http://localhost:8080/rest/spruches/

{
    "name": "Petra",
    "text": "hola", 
    "anspruch": 80
}


###

POST http://localhost:8080/rest/spruches/

{
    "name": "Karl",
    "text": "hallo", 
    "anspruch": 120
}


###

POST http://localhost:8080/rest/spruches/

{
    "name": "Pascale",
    "text": "Ich stinke", 
    "anspruch": 55
}

###

DELETE http://localhost:8080/rest/spruches/1431

###

PUT http://localhost:8080/rest/spruches/1429

{
    "name": "Susi",
    "text": "halli hallo", 
    "anspruch": 92
}

###

GET http://localhost:8080/rest/spruches/?page=0&size=5&sort=anspruch,asc

###

GET http://localhost:8080/rest/spruches/?page=0&size=5&sort=name,desc

###

GET http://localhost:8080/rest/spruches/?page=2&size=5&sort=anspruch,asc

###

GET http://localhost:8080/rest/spruches/?page=0&size=5&sort=anspruch,asc

###

GET http://localhost:8080/rest/spruches/?page=1&size=5&sort=anspruch,asc

###

GET http://localhost:8080/rest/tags

###

POST http://localhost:8080/rest/tags/

{
    "name": "duoop"
}

###

POST http://localhost:8080/rest/tags/

{
    "name": "was geht"
}

###

POST http://localhost:8080/rest/tags/

{
    "name": "hallo"
}

#Aufgabe 7

###

POST http://localhost:8080/rest/spruches/

{
    "name": "Cathi",
    "text": "Ich ziehe bald in mein neues Haus", 
    "anspruch": 60
}

###

GET http://localhost:8080/rest/spruches/1498/tags

###

POST http://localhost:8080/rest/spruches/1/tags
Content-Type: text/uri-list

http://localhost:8080/rest/tags/4

###

GET http://localhost:8080/rest/spruches/1498/tags

###

#DELETE ....

